server:
  port: 8081
spring:
  application:
    name: spring-7-resttemplate
  security:
    oauth2:
      # Aplicação que protege APIs e valida JWT
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      # Aplicação que faz Login via OAuth2 / OIDC
      client:
        # Define os clientes OAuth2 da aplicação
        registration:
          springauth:
            provider: springauth
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope:
              - message.read
              - message.write
        # Define os detalhes do provedor OAuth2
        provider:
          springauth:
            authorization-uri: http://localhost:9000/auth2/authorize
            token-uri: http://localhost:9000/oauth2/token

rest:
  template:
    rootUrl: http://localhost:8080

debug: true