server:
  port: 8083
spring:
  application:
    name: spring-7-reactive-mongo
  docker:
    compose:
      enabled: false
  mongodb:
    host: mongo
    port: 27017
    username: root
    password: root
    database: sfg
    authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

# Actuator Kubernetes Integration
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
logbook:
  write:
    max-body-size: -1

logging:
  level:
    org.zalando.logbook: trace