spring:
  application:
    name: spring-7-reactive-mongo
  mongodb:
    host: localhost
    port: 27017
    username: root
    password: root
    database: sfg
    authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
debug: true