spring:
  application:
    name: spring-7-reactive-mongo
  mongodb:
    # protocol://username:password@host:port/database?authentication-database
    uri: mongodb://root:root@localhost:27017/sfg?authSource=spring-reactive-mongo&directConnection=true
