server:
  port: 9000

spring:
  application:
    name: spring-7-auth-server

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true