# application.yaml
spring:
  application:
    name: spring-7-rest-mvc

  flyway:
    enabled: false

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
    user:
      name: user1
      password: password

  cache:
    cache-names:
      - beerCache
      - beerListCache
      - customerCache
      - customerListCache

  kafka:
    consumer:
      group-id: sfg
      auto-offset-reset: earliest
      key-deserialize: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  level:
    org.zalando.logbook: trace
    org.springframework: debug
#    org.springframework.security: trace