# application.yaml
spring:
  application:
    name: spring-7-rest-mvc
  flyway:
    enabled: true
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
    user:
      name: user1
      password: password
  # Java Virtual Threads
  threads:
    virtual:
      enabled: true
  # caching
  cache:
    cache-names:
      - beerCache
      - beerListCache
      - customerCache
      - customerListCache

#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql

# Actuator Kubernetes Integration
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  level:
    root: info # em produção
    sql: warn # em produção
    org.zalando.logbook: trace  # em produção trocar para INFO
    org.springframework: debug