server:
  port: 8081
spring:
  application:
    name: spring-7-webclient
  security:
    oauth2:
      client:
        registration:
          springauth:
            provider: springauth
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope:
              - message.read
              - message.write
        provider:
          springauth:
            token-uri: http://localhost:9000/oauth2/token

webclient:
  root-url: http://localhost:8080