server:
  port: 8082
spring:
  application:
    name: spring-7-reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logbook:
    write:
      max-body-size: -1

logging:
  level:
    org.zalando.logbook: trace
