# application-docker.yaml
server:
  port: 8080

spring:
  application:
    name: spring-7-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: spring-7-rest-mvc
              uri: http://rest-mvc:8080
              predicates:
                - Path=/api/v1/**
            - id: spring-7-reactive
              uri: http://reactive:8080
              predicates:
                - Path=/api/v2/**
            - id: spring-7-reactive-mongo
              uri: http://reactive-mongo:8080
              predicates:
                - Path=/api/v3/**
            - id: spring-7-auth-server
              uri: http://auth-server:9000
              predicates:
                - Path=/oauth2/**
              filters:
                - name: SetRequestHostHeader
                  args:
                    host: auth-server

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.zalando.logbook: trace